name: moneylog_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  speech_to_text: ^7.3.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GmarketSans
      fonts:
        - asset: fonts/GmarketSansTTFMedium.ttf
        - asset: fonts/GmarketSansTTFBold.ttf
          weight: 700
        - asset: fonts/GmarketSansTTFLight.ttf
          weight: 300
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Medium.otf
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
